### ISSUE TITLE
hoi

### ISSUE THREAD

**Issue by CherwinKramer** [davinci-ao17/git-lpiao17xx#1]

**Comment by oga-sven** [comment]
heb je al geprobeerd de stekker d'r uit en d'r weer in te doen?

**Comment by voodootje0** [comment]
doei

**Comment by oga-sven** [comment]
graag gedaan!

**Comment by CherwinKramer** [comment]
Dank u wel dat heeft geholpen! Heb ook mn toetsenbord schoongemaakt met een flesje water.

**Comment by oga-sven** [comment]
probeer liquid nitrogin te geruiken! helpt!
neem er ook gerust een slokje van! beter dan pepermunt!

**Comment by CherwinKramer** [comment]
Het perfecte koelingssysteem is je laptop in een bak water te leggen. Werkt perfect

**Comment by oga-sven** [comment]
ik denk dat je een poster van spiderman moet ophangen aan je achterdeur en daar ongeveer een half uurtje naar moet staren, om vervolgens in zo'n hallucinerende trip te komen dat je elke geheim van het universum weet, en dat uiteindelijk verspild aan gebouwen maken in minecraft
